services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: reserva_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - redis
    networks:
      - reserva-network

  nginx:
    image: nginx:1.25-alpine
    container_name: reserva_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - reserva-network

  db:
    image: postgres:16
    container_name: reserva_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-reservas}
      POSTGRES_USER: ${DB_USERNAME:-laravel}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - reserva-network

  redis:
    image: redis:7.2-alpine
    container_name: reserva_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - reserva-network

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: reserva_worker
    restart: unless-stopped
    command: "nodemon --config docker/nodemon.json"
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
      - db
    networks:
      - reserva-network

networks:
  reserva-network:
    driver: bridge

volumes:
  db_data:
    driver: local
